// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413120540_InicializarBaseDeDatos")]
    partial class InicializarBaseDeDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WebApi.Data.TA_LISTA_USUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ESTADO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FECHA_AGREGADO")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PUNTUACION")
                        .HasColumnType("INTEGER");

                    b.Property<int>("USUARIO_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VIDEOJUEGO_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("TA_LISTA_USUARIO");
                });

            modelBuilder.Entity("WebApi.Data.TA_USUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FECHA_REGISTRO")
                        .HasColumnType("TEXT");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TA_USUARIO");
                });

            modelBuilder.Entity("WebApi.Data.TA_VIDEOJUEGO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FECHA_LANZAMIENTO")
                        .HasColumnType("TEXT");

                    b.Property<string>("GENERO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IMAGEN_URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PLATAFORMA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RAWG_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TITULO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TA_VIDEOJUEGO");
                });
#pragma warning restore 612, 618
        }
    }
}
